---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-exporter
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./.monitoring/node-exporter/components
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: node-exporter
  targetNamespace: monitoring
  timeout: 3m0s
  wait: true
