---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 1m0s
  path: nginx-ingress/components
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: nginx-ingress
  timeout: 3m0s
  wait: true
