---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1m0s
  path: components
  prune: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: monitoring
  targetNamespace: monitoring
  timeout: 3m0s
  wait: true
